### ISSUE TITLE
Commit 884da39 wouldn't boot

### ISSUE THREAD

**Issue by litui** [SynthstromAudible/DelugeFirmware#113]
Using 7seg deluge, tested before and after this merge. Loading firmware from SD card resulted in unresponsive Deluge on commits after 884da398a3b622bdab414b420041cac867b26008 until the change was reverted.

@stellar-aria has a bug fix in the works.

**Comment by litui** [comment]
Reopening issue as work on the bug gets resolved, but @bobtwinkles 's PR reverted the change so this is no longer urgent.

**Comment by stellar-aria** [comment]
The problem was discovered to be two bugs: one, in the linkerscript with ordering and offset, and the second (much more complicated one) being related to init order of global variables, which is technically undefined behavior.

As of current work at 8d402b713a495cc20a4f2ebd1a45c1909b6a58ed, the linkerscript is confirmed working and acting as normal.

Next steps involve slowly removing manual initialization in favor of global initializers until we find the culprit out-of-order initializer that is causing E140.
