### ISSUE TITLE
Can no longer scroll through available audio clips in song view

### ISSUE THREAD

**Issue by baymud** [SynthstromAudible/DelugeFirmware#1148]
### Please describe the problem:

In some cases you want to clone an existing audio clip then use the select knob to scroll through the available audio clip numbers in your project and select a different one (audio1, audio2, etc.). 

This used to be possible via song view by holding a pad of the audio clip you wanted to change while turning the select knob, but now it says "CANT". (this method still works in C.1.0.1, but not the latest nightly)

However, this can still be done by entering the specific clip you'd like to change and turning the select knob there, so it's still possible, just not via song view for some reason. 

(It was suggested #970 may be responsible for this bug, as that's the only PR to tackle audio clips)

### What is the expected behavior?

Users should be able to change the audio clip number in both song view and in the clip itself. 

### Is there a relevant Pull request?

970

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Nightly

**Comment by m-m-adams** [comment]
This is somewhat intentional - #1016 enables changing the synth preset or MIDI channel for an entire track from song view, or converting a whole track from a synth to MIDI. You are able to change a single clip's preset from clip view

This change unified some existing behaviour so that from song or arranger view changing a clip always changes the whole track, and from clip view it changes just the single clip if possible. Previously whether scrolling presets would affect all clips in a track or a single one depended on the song structure in arranger view and so was not consistent in song or clip view.

As this change can't benefit audio clips it might be possible to revert it just for them. I'm closing the issue but open to a PR doing that
