### ISSUE TITLE
Arpeggiator tweaks 

### ISSUE THREAD

**Issue by m-m-adams** [SynthstromAudible/DelugeFirmware#1259]
- Ratchet doesn't work with playback stopped
- Ratchet doesn't work on MIDI notes
- Arpeggiator menu classes are redundant 

@soymonitus

**Comment by soymonitus** [comment]
What is "arpegiator menus redundant"?

**Comment by soymonitus** [comment]
Ohh I know what you mean. Gate was already like that from before I started coding, and it is because the Params are different for synth and for midi clips. There is a different version of the menu items for each. It seems that Params can't have the same behaviour when for midi clips, they save the value differently. I just mimicked Gate for my new params.

**Comment by m-m-adams** [comment]
No, the gate and sequence length classes are identical. There is no need for them to be seperate classes. 

<img width="1581" alt="image" src="https://github.com/SynthstromAudible/DelugeFirmware/assets/52469396/7e6b8d55-78d6-4743-a775-14d7ee6c2018">

Same situation for ratchet and ratchet probability

**Comment by soymonitus** [comment]
Ohh i see

**Comment by soymonitus** [comment]
Redundant arpeggiator menu classes is fixed here:
https://github.com/SynthstromAudible/DelugeFirmware/pull/1271
