### ISSUE TITLE
Sysex firmware loading broken by bootloader alignment workaround

### ISSUE THREAD

**Issue by sapphire-arches** [SynthstromAudible/DelugeFirmware#1429]
The alignment hack introduced in #1411 breaks sysex firmware loading because that process relies on the size of the .bin file to determine the size to send, but the sent size might not match the size declared in the binary itself (as parsed by the loadfw infrastructure) because the padding is not included.

The bootloader might also be loading garbage off the disk in this situation, which is probably fine since we zero and treat that as heap memory, but that probably needs to be verified.

See also #1084.

**Comment by m-m-adams** [comment]
Yeah the bootloader is reading garbage from flash. The firmware updater uses the actual file size and not the size reported in the binary so it's fine, 

Two possible fixes:
1. Have the sysex loader use the file size instead of "end"
2. actually put something at the location of "end" so the linker pads the file out
