### ISSUE TITLE
Sounds can click when parameters are rapidly modulated.

### ISSUE THREAD

**Issue by sapphire-arches** [SynthstromAudible/DelugeFirmware#1989]
Large changes in many parameters (filter cutoff/resonance, master level, etc) cause clicks, we should probably use crossfade logic like what was added added for #932 to avoid this. It would require rendering the voice twice for a window but maybe that perf hit is worth avoiding the clicks?

**Comment by ok-reza** [comment]
I think this particular issue is expected based on the extreme modulation, I'm specifically noticing anything related to possible clicks is due to master level more than I am with filter/resonance.  I can replicate a similar experience you've detailed with other analog synths, (they just don't have access to increase osc1 level if it's already all the way up, unlike the Deluge). Rendering double the voices seems like it would add up, and this feels more like user-side problem/inexperience than a particular audio issue..

**Comment by sapphire-arches** [comment]
yeah some of it is user error, but especially with automation view it's really easy to create automation that clicks

**Comment by sapphire-arches** [comment]
maybe there's nothing we can do, but I think with some clever math we can bandlimit automation

**Comment by m-m-adams** [comment]
Maybe we can put a temporary lpf on automation?

New value = (current value + automated value)/2 for like 2-3 render windows after a value change would probably do it
