### ISSUE TITLE
Trigger Clock Jitter in Community Editions

### ISSUE THREAD

**Issue by acook** [SynthstromAudible/DelugeFirmware#2247]
### Please describe the problem:

There is clock jitter in the community edition that can cause noticeable BPM instability in downstream devices. This jitter is not present on the official firmware versions.

---

I'm seeing pretty significant jitter with a Deluge's 24 PPQN clock being detected by my Pam's as rapidly shifting between 118-121 BPM from a target 120 BPM.

This 3 BPM variation would be equivalent to a wow & flutter of 2.5%, well above the 0.2-0.25% threshold often said to be the audible minimum. This of course obliterates tempo-synced delays and makes recordings effectively impossible to align with other takes or layers.

---

What's interesting though is that if I have a set of 128th notes playing in a synth clip with arpeggiator enabled, the BPM seems to stabilize. This stabilizing effect is noticeable up until around 8th notes. I'm sure the jitter is still there, but the synth is forcing syncs often enough that the Pam's can smooth it out.

I sometimes noticed the clock locking in with CV clips, but it was not as reliable. Drum kits seem to have no effect even at very fast trigger rates.

Either way, if the clip is not actively playing notes then the stabilizing effect is absent.

---

Created per https://github.com/SynthstromAudible/DelugeFirmware/pull/2145#issuecomment-2211442859

---

Jitter may also be present on MIDI, but is less noticeable.

### What is the expected behavior?

Clock jitter should ideally be less 0.2%.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Release 1.1/Beethoven

### What is the firmware name:

cedf24a

### If possible provide the steps to reproduce the issue and upload additional media:

1. Enable trigger clock
2. Connect gate output to desired downstream clock with BPM readout
3. Set both to 24 PPQN (other values also show this effect, but 24 may make it more obvious)
4. Press `play` on the Deluge
5. Observe inconsistent BPM

**Comment by m-m-adams** [comment]
![image](https://github.com/SynthstromAudible/DelugeFirmware/assets/52469396/92eefd26-7927-41c2-bc11-4ccb2d205f5b)

Measured and plotted jitter, confirming the expectation for how it should be behaving right now

The middle values are acceptable, the two peaks at +-2.9ms are not. That's the max window render time of 128 samples so I believe this is occurring when there's a particularly long render for any reason

Note that the sequencer and audio are tightly linked, so that is combined time to process the current position and to render audio
