### ISSUE TITLE
Saving the brightness settings

### ISSUE THREAD

**Issue by n3ptun3s** [SynthstromAudible/DelugeFirmware#226]
It would be great to save the brightness settings permanently.

**Comment by m-m-adams** [comment]
Hi @n3ptun3s, welcome to the community github and thanks for bringing up this issue. In order to keep the issues more usable for development we are trying to keep them to bug reports and current work in progress. With that in mind would you be able to close this and #225 and bring up your suggestions in the discussions tab as an idea instead?
