### ISSUE TITLE
Random and S&H LFOs, triplet and dotted LFO sync

### ISSUE THREAD

**Issue by phfalk** [SynthstromAudible/DelugeFirmware#26]
I always wanted to have some more randomness for modulation that changes more frequently than the "Random" modulation source which only outputs a new random value every time a note is triggered. How I imagine this to work:

  - [x]  Add LFO that just outputs a random value every time it is called. This might be a little too jittery to be useful
    - sort of working but more noisy than musical 
  - [x]  Add another LFO that takes a random value and holds it for some time until a new random value is generated
  - [x] Explore what kinds of smoothing or restrictions in terms of how far subsequent values can be from each other would be useful
  - [x] Now that I understand more about how the LFOs work, next step could be triplet or maybe even dotted LFO sync timings

**Comment by alex-reid** [comment]
I've been looking into dotted notes for sync settings. From what I can gather at a high level, sync setting are stored as an `int` from 0 to 9 with that number being a divisor for the sync length hence why the sync settings are whole steps. My thoughts around this are that maybe implementing a `bool` for dotted notes along with the 0 to 9 sync settings might be the way to go.

Looking at @dctucker's excellent class diagrams, the UI side of things is handled by [MenuItemSyncLevel](https://dctucker.github.io/DelugeFirmware/docs/de/d7d/class_menu_item_sync_level.html) and is fed to the arp, delay, lfo and sidechain. 

I can't currently get the toolchain set up because i'm on a mac, but if I did, I'd probably approach it by trying to get the UI working and then delve into getting it hooked up to the individual things that work off that.

**Comment by phfalk** [comment]
Corresponding MR was merged

**Comment by manysounds** [comment]
Current community build (c95a27c) LFO shape buttons hang the machine.

**Comment by bobtwinkles** [comment]
That was a bug due to the menu item refactor, please try the latest nightly: https://github.com/SynthstromAudible/DelugeFirmware/actions/runs/5827496457

The pages site build is broken so it is currently out of date.

**Comment by bobtwinkles** [comment]
Actually that won't have some other fixes to know bugs, latest build is here: https://github.com/SynthstromAudible/DelugeFirmware/actions/runs/5830090263

In the future, please prefer opening new bugs to commenting on closed ones :sweat_smile:
