### ISSUE TITLE
7SEG Emulation Mode

### ISSUE THREAD

**Issue by bobtwinkles** [SynthstromAudible/DelugeFirmware#41]
@bfredl mentioned this on the discord, https://discord.com/channels/608916579421257728/1107026299945496577/1116778630656299098.

> maybe this already has been discussed but one thing which I'd like to see: A "virtual 7seg" build mode. Build the entire UI/menu system with HAVE_OLED set to false, but add a separate flag to still build the low-level oled driver. then write an oled rendering routine which emulates the 7seg display.
> The main usecase is of course debugging/testing ui code, if you have an OLED deluge you can debug how your changes will behave on a 7seg deluge

In the general spirit of Synthstrom's approach to supporting the 7seg, we probably want to make sure any features (enabled by default only?) that get merged to `community` support the 7seg well.

--- 

Technical sketch:
- Use the existing `HAVE_OLED` to mean that we're using the OLED UI, to minimize churn in the upper/UI layers
- Introduce a new define, `DELUGE_DISPLAY` (bikeshed name) similar to `DELUGE_MODEL` which is used by the lower layers to switch between physical OLED and 7SEG output.

**Comment by ok-reza** [comment]
I've uploaded assets and some guides based on the dimensions of the OLED's screen.

Currently, I've created two different font styles, Regular and Bold. Regular resembles the weight and spacing of the 7-SEG Deluge the most, whereas Bold takes liberties for better readability. (Excuse any anti-aliasing GitHub may introduce to the following images)
![7-SEG_for_OLED_Regular_Screen](https://github.com/SynthstromAudible/DelugeFirmware/assets/136033640/24ed4206-559e-45c5-8f51-cc9df68fe54a)
![7-SEG_for_OLED_Bold_Screen](https://github.com/SynthstromAudible/DelugeFirmware/assets/136033640/413a7fa2-9ece-4b33-a44e-0582d1e180fc)

However, the Deluge's 7-SEG display is also slanted, I could make versions like that for both Regular and Bold pretty easily now, however I'm holding off until further progress is made with the current assets.  Readability will be a little more odd with them slanted anyway. Also there may be issues with incorporating the period (.) with slanted text due to it sharing space with the slanted text directly above it. Just depends on how things are implemented I suppose!

Once the fonts are properly implemented, the following guides will assist in formatting/arranging the two font styles properly on screen.
![7-SEG_for_OLED_Regular_Screen_Guide](https://github.com/SynthstromAudible/DelugeFirmware/assets/136033640/2240e70c-259d-43cd-b148-c09047585d03)

![7-SEG_for_OLED_Bold_Screen_Guide](https://github.com/SynthstromAudible/DelugeFirmware/assets/136033640/e41f1499-cacf-457a-9fe0-92890a39a5ad)

Also, while making these I wondered if displaying text via glyphs (how OLED seems to currently handle text) would be disadvantageous to displaying text by referencing which letters call for which segments to be 'lit'. There are a few formatting rules with the 7SEG display which may make it tricky to use with the OLED's text display code without some more finessing. That being said, I'm no programmer!

Happy to assist with design/art/assets where possible!

**Comment by soymonitus** [comment]
Wow, love this idea

**Comment by designerfuzzi** [comment]
@ok-reza in case you want to tinker with it, i recreated Deluges italic 7OLED font as `ttf` and `otf` a while ago and never really used it. [ttf on googledrive](https://drive.google.com/file/d/1mIYeQVh8dRzw-hmYbYVczIWltCpTWS9K/view?usp=sharing)
and [otf on googledrive](https://drive.google.com/file/d/1GvJEbCXla8DONm74kCjDjBTvFL4ButBB/view?usp=sharing)

**Comment by annaluiseblume** [comment]
I would love to see some of this inspirational work being factored in:

https://youtu.be/RTB5XhjbgZA

**Comment by m-m-adams** [comment]
Closing this as completed via https://bfredl.github.io/delugeclient/app.html and #192
