### ISSUE TITLE
Make sure stealable memory is deallocated at the right time

### ISSUE THREAD

**Issue by PaulFreund** [SynthstromAudible/DelugeFirmware#643]
One way or another stealable sample memory is not deallocated efficiently at the moment. Secondary mechanisms are needed to reclaim memory where it coul already have been freed or queued to be freed. A possible cause is that samples have to many reasons attached to them (usage counter).

What can often be seen before secondary reclaim begins is:
```
stole and grabbed neighbouring stuff too...........
```

This is a reminder to find a solution

**Comment by m-m-adams** [comment]
The message "stole and grabbed neighbouring stuff too..........." indicates that there are no sample clusters available to steal directly (since if there were it wouldn't need neighbors)

Then stealing the control sample deallocates the remaining clusters, regardless of how many reasons they have left and that's the self-healing part

I believe this supports a memory leak (lingering reasons) on sample clusters

**Comment by m-m-adams** [comment]
Moving this to release-1.0 due to the impact on audio recording
